import { useState } from 'react'
import { Calendar, CalendarPlus, Download, Check, X, Apple, Loader2, ExternalLink, Clock, FileText, CalendarDays } from 'lucide-react'

interface CalendarSyncProps {
  lessonId?: string
  curriculumId?: string
  lessonTitle: string
  lessonPassage?: string
  durationMinutes?: number
}

export function CalendarSync({ lessonId, curriculumId, lessonTitle, lessonPassage, durationMinutes = 45 }: CalendarSyncProps) {
  const [showModal, setShowModal] = useState(false)
  const [selectedProvider, setSelectedProvider] = useState<'google' | 'outlook' | 'apple' | null>(null)
  const [eventDate, setEventDate] = useState('')
  const [eventTime, setEventTime] = useState('09:00')
  const [successMessage, setSuccessMessage] = useState<string | null>(null)

  // Generate ICS content locally (no API needed)
  const generateICSContent = (startDate: Date, endDate: Date): string => {
    const uid = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}@biblelessonplanner.com`
    const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
    const start = startDate.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
    const end = endDate.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
    
    const description = `Passage: ${lessonPassage || 'N/A'}\\n\\nGenerated by Bible Lesson Planner`
    
    return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Bible Lesson Planner//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:${uid}
DTSTAMP:${now}
DTSTART:${start}
DTEND:${end}
SUMMARY:Bible Lesson: ${lessonTitle}
DESCRIPTION:${description}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR`
  }

  // Download ICS file
  const downloadICS = () => {
    if (!eventDate || !eventTime) return
    
    const startDate = new Date(`${eventDate}T${eventTime}:00`)
    const endDate = new Date(startDate.getTime() + durationMinutes * 60000)
    
    const icsContent = generateICSContent(startDate, endDate)
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `bible-lesson-${lessonTitle.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 30)}.ics`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    setSuccessMessage('Calendar file downloaded!')
    setTimeout(() => {
      setSuccessMessage(null)
      setShowModal(false)
    }, 2000)
  }

  // Generate Google Calendar URL (opens in new tab)
  const getGoogleCalendarUrl = (): string => {
    if (!eventDate || !eventTime) return ''
    
    const startDate = new Date(`${eventDate}T${eventTime}:00`)
    const endDate = new Date(startDate.getTime() + durationMinutes * 60000)
    
    // Format: YYYYMMDDTHHmmss
    const formatDate = (d: Date) => d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
    
    const params = new URLSearchParams({
      action: 'TEMPLATE',
      text: `Bible Lesson: ${lessonTitle}`,
      details: `Passage: ${lessonPassage || 'N/A'}\n\nGenerated by Bible Lesson Planner`,
      dates: `${formatDate(startDate)}/${formatDate(endDate)}`,
    })
    
    return `https://calendar.google.com/calendar/render?${params.toString()}`
  }

  // Generate Outlook Calendar URL (opens in new tab)
  const getOutlookCalendarUrl = (): string => {
    if (!eventDate || !eventTime) return ''
    
    const startDate = new Date(`${eventDate}T${eventTime}:00`)
    const endDate = new Date(startDate.getTime() + durationMinutes * 60000)
    
    const params = new URLSearchParams({
      path: '/calendar/action/compose',
      rru: 'addevent',
      subject: `Bible Lesson: ${lessonTitle}`,
      body: `Passage: ${lessonPassage || 'N/A'}\n\nGenerated by Bible Lesson Planner`,
      startdt: startDate.toISOString(),
      enddt: endDate.toISOString(),
    })
    
    return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`
  }

  // Open calendar in new tab
  const openCalendar = (provider: 'google' | 'outlook') => {
    if (!eventDate || !eventTime) return
    
    const url = provider === 'google' ? getGoogleCalendarUrl() : getOutlookCalendarUrl()
    window.open(url, '_blank')
    
    setSuccessMessage(`Opened ${provider === 'google' ? 'Google' : 'Outlook'} Calendar!`)
    setTimeout(() => {
      setSuccessMessage(null)
      setShowModal(false)
    }, 2000)
  }

  const providers = [
    { 
      id: 'google', 
      name: 'Google', 
      icon: <Calendar className="w-5 h-5" strokeWidth={1.5} />, 
      gradient: 'from-blue-500 to-blue-600',
      lightBg: 'bg-blue-50 dark:bg-blue-900/20',
      borderColor: 'border-blue-200 dark:border-blue-800/50',
      action: () => openCalendar('google')
    },
    { 
      id: 'outlook', 
      name: 'Outlook', 
      icon: <CalendarPlus className="w-5 h-5" strokeWidth={1.5} />, 
      gradient: 'from-sky-500 to-cyan-600',
      lightBg: 'bg-sky-50 dark:bg-sky-900/20',
      borderColor: 'border-sky-200 dark:border-sky-800/50',
      action: () => openCalendar('outlook')
    },
    { 
      id: 'apple', 
      name: 'Apple / Other', 
      icon: <Apple className="w-5 h-5" strokeWidth={1.5} />, 
      gradient: 'from-stone-600 to-stone-700',
      lightBg: 'bg-stone-100 dark:bg-stone-800/50',
      borderColor: 'border-stone-300 dark:border-stone-600',
      action: downloadICS
    },
  ]

  const isDateTimeSelected = eventDate && eventTime

  return (
    <>
      {/* Success Toast */}
      {successMessage && (
        <div className="fixed top-20 left-1/2 -translate-x-1/2 z-50 animate-in fade-in slide-in-from-top-2 duration-300">
          <div className="flex items-center gap-3 px-6 py-4 rounded-2xl bg-gradient-to-r from-emerald-500 to-emerald-600 text-white shadow-2xl shadow-emerald-500/30">
            <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center">
              <Check className="w-5 h-5" strokeWidth={2.5} />
            </div>
            <span className="font-semibold">{successMessage}</span>
          </div>
        </div>
      )}

      {/* Trigger Button */}
      <button
        onClick={() => setShowModal(true)}
        className="flex items-center justify-center gap-2 w-40 py-2.5 rounded-lg bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-sm font-semibold border border-amber-200 dark:border-amber-800/50 hover:bg-amber-100 dark:hover:bg-amber-900/50 transition-colors shadow-sm"
        data-testid="calendar-sync-btn"
      >
        <Calendar className="w-4 h-4" strokeWidth={2} />
        <span>Add to Calendar</span>
      </button>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={() => setShowModal(false)} />
          
          {/* Modal Container */}
          <div className="relative w-full max-w-lg overflow-hidden">
            {/* Gradient Border Wrapper */}
            <div className="rounded-3xl bg-gradient-to-br from-amber-400 via-orange-400 to-amber-500 p-[2px] shadow-2xl shadow-amber-500/20">
              <div className="rounded-3xl bg-white dark:bg-stone-900 overflow-hidden">
                
                {/* Header */}
                <div className="relative px-6 pt-6 pb-5 bg-gradient-to-br from-amber-50 via-white to-orange-50/50 dark:from-amber-950/30 dark:via-stone-900 dark:to-orange-950/20 border-b border-amber-100 dark:border-amber-900/30">
                  <div className="absolute top-0 right-0 w-32 h-32 -translate-y-16 translate-x-16">
                    <div className="w-full h-full rounded-full bg-gradient-to-br from-amber-200/30 to-orange-200/10 blur-2xl" />
                  </div>
                  
                  <div className="relative flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center shadow-lg shadow-amber-500/30 rotate-3 transform">
                        <CalendarDays className="w-7 h-7 text-white" strokeWidth={1.5} />
                      </div>
                      <div>
                        <h3 className="text-2xl font-bold text-stone-900 dark:text-stone-50" style={{ fontFamily: 'Crimson Text, serif' }}>
                          Schedule Lesson
                        </h3>
                        <p className="text-sm text-stone-500 dark:text-stone-400">Add to your calendar</p>
                      </div>
                    </div>
                    <button 
                      onClick={() => setShowModal(false)} 
                      className="w-10 h-10 rounded-xl bg-white dark:bg-stone-800 border border-stone-200 dark:border-stone-700 flex items-center justify-center hover:bg-stone-50 dark:hover:bg-stone-700 hover:border-stone-300 transition-all"
                    >
                      <X className="w-5 h-5 text-stone-400" strokeWidth={1.5} />
                    </button>
                  </div>
                </div>

                {/* Content */}
                <div className="p-6 space-y-5">
                  {/* Lesson Info Card */}
                  <div className="relative rounded-2xl bg-gradient-to-br from-amber-50 to-orange-50 dark:from-amber-950/20 dark:to-orange-950/10 border border-amber-200/50 dark:border-amber-800/30 p-5 overflow-hidden">
                    <div className="absolute top-0 right-0 w-20 h-20 -translate-y-10 translate-x-10">
                      <div className="w-full h-full rounded-full bg-gradient-to-br from-amber-300/20 to-transparent blur-xl" />
                    </div>
                    
                    <div className="relative flex items-start gap-4">
                      <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center shadow-md shadow-amber-500/25 flex-shrink-0">
                        <FileText className="w-6 h-6 text-white" strokeWidth={1.5} />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="font-bold text-stone-900 dark:text-stone-100 text-base truncate" style={{ fontFamily: 'Crimson Text, serif' }}>
                          {lessonTitle}
                        </p>
                        {lessonPassage && (
                          <p className="text-sm text-amber-700 dark:text-amber-400 mt-1 font-medium">{lessonPassage}</p>
                        )}
                        <div className="flex items-center gap-2 mt-2">
                          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-xs font-semibold">
                            <Clock className="w-3.5 h-3.5" strokeWidth={2} />
                            {durationMinutes} minutes
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Date & Time Selection */}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-semibold text-stone-700 dark:text-stone-300 mb-2">
                        Date
                      </label>
                      <input
                        type="date"
                        value={eventDate}
                        onChange={(e) => setEventDate(e.target.value)}
                        min={new Date().toISOString().split('T')[0]}
                        className="w-full px-4 py-3 rounded-xl border-2 border-stone-200 dark:border-stone-700 bg-white dark:bg-stone-800 text-stone-900 dark:text-stone-100 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-400 transition-all text-sm font-medium"
                        data-testid="calendar-date-input"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-semibold text-stone-700 dark:text-stone-300 mb-2">
                        Time
                      </label>
                      <input
                        type="time"
                        value={eventTime}
                        onChange={(e) => setEventTime(e.target.value)}
                        className="w-full px-4 py-3 rounded-xl border-2 border-stone-200 dark:border-stone-700 bg-white dark:bg-stone-800 text-stone-900 dark:text-stone-100 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-400 transition-all text-sm font-medium"
                        data-testid="calendar-time-input"
                      />
                    </div>
                  </div>

                  {/* Calendar Provider Selection */}
                  <div>
                    <label className="block text-sm font-semibold text-stone-700 dark:text-stone-300 mb-3">
                      Choose your calendar
                    </label>
                    <div className="grid grid-cols-3 gap-3">
                      {providers.map(provider => (
                        <button
                          key={provider.id}
                          onClick={() => {
                            setSelectedProvider(provider.id as 'google' | 'outlook' | 'apple')
                            if (isDateTimeSelected) {
                              provider.action()
                            }
                          }}
                          disabled={!isDateTimeSelected}
                          className={`relative p-4 rounded-xl border-2 text-center transition-all duration-300 overflow-hidden group disabled:opacity-50 disabled:cursor-not-allowed ${
                            selectedProvider === provider.id
                              ? 'border-amber-400 dark:border-amber-600 bg-gradient-to-br from-amber-50 to-orange-50 dark:from-amber-950/30 dark:to-orange-950/20 shadow-lg shadow-amber-500/10'
                              : `${provider.borderColor} ${provider.lightBg} hover:border-amber-300 dark:hover:border-amber-700`
                          }`}
                          data-testid={`provider-${provider.id}`}
                        >
                          <div className={`w-10 h-10 mx-auto mb-2 rounded-xl flex items-center justify-center transition-all duration-300 ${
                            selectedProvider === provider.id 
                              ? 'bg-gradient-to-br from-amber-400 to-orange-500 shadow-md shadow-amber-500/25 text-white' 
                              : `bg-gradient-to-br ${provider.gradient} text-white shadow-md group-hover:scale-110`
                          }`}>
                            {provider.icon}
                          </div>
                          <span className={`text-sm font-semibold ${
                            selectedProvider === provider.id 
                              ? 'text-amber-700 dark:text-amber-400' 
                              : 'text-stone-700 dark:text-stone-300'
                          }`}>
                            {provider.name}
                          </span>
                          {provider.id !== 'apple' && (
                            <div className="flex items-center justify-center gap-1 mt-1 text-xs text-stone-400">
                              <ExternalLink className="w-3 h-3" />
                              <span>Opens web</span>
                            </div>
                          )}
                          {provider.id === 'apple' && (
                            <div className="flex items-center justify-center gap-1 mt-1 text-xs text-stone-400">
                              <Download className="w-3 h-3" />
                              <span>Downloads .ics</span>
                            </div>
                          )}
                        </button>
                      ))}
                    </div>
                    
                    {!isDateTimeSelected && (
                      <p className="text-center text-sm text-stone-400 mt-3">
                        Select a date and time first
                      </p>
                    )}
                  </div>
                </div>

                {/* Footer */}
                <div className="flex items-center justify-end gap-3 px-6 py-5 border-t-2 border-stone-100 dark:border-stone-800 bg-gradient-to-r from-stone-50 to-stone-100/50 dark:from-stone-900/50 dark:to-stone-800/30">
                  <button
                    onClick={() => setShowModal(false)}
                    className="px-6 py-2.5 rounded-xl text-sm font-semibold text-stone-500 dark:text-stone-400 hover:bg-stone-200 dark:hover:bg-stone-700 transition-colors"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
