/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgressInfoRouteImport } from './routes/progress-info'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CurriculumInfoRouteImport } from './routes/curriculum-info'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series/$seriesId'
import { Route as ScripturePsalmsWisdomRouteImport } from './routes/scripture/psalms-wisdom'
import { Route as ScriptureOldTestamentRouteImport } from './routes/scripture/old-testament'
import { Route as ScriptureNewTestamentRouteImport } from './routes/scripture/new-testament'
import { Route as ScriptureGospelsRouteImport } from './routes/scripture/gospels'
import { Route as ScriptureEpistlesRouteImport } from './routes/scripture/epistles'
import { Route as PrintLessonIdRouteImport } from './routes/print.$lessonId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson/$lessonId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressInfoRoute = ProgressInfoRouteImport.update({
  id: '/progress-info',
  path: '/progress-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumInfoRoute = CurriculumInfoRouteImport.update({
  id: '/curriculum-info',
  path: '/curriculum-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScripturePsalmsWisdomRoute = ScripturePsalmsWisdomRouteImport.update({
  id: '/scripture/psalms-wisdom',
  path: '/scripture/psalms-wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptureOldTestamentRoute = ScriptureOldTestamentRouteImport.update({
  id: '/scripture/old-testament',
  path: '/scripture/old-testament',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptureNewTestamentRoute = ScriptureNewTestamentRouteImport.update({
  id: '/scripture/new-testament',
  path: '/scripture/new-testament',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptureGospelsRoute = ScriptureGospelsRouteImport.update({
  id: '/scripture/gospels',
  path: '/scripture/gospels',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptureEpistlesRoute = ScriptureEpistlesRouteImport.update({
  id: '/scripture/epistles',
  path: '/scripture/epistles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintLessonIdRoute = PrintLessonIdRouteImport.update({
  id: '/print/$lessonId',
  path: '/print/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-info': typeof CurriculumInfoRoute
  '/features': typeof FeaturesRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/lessons': typeof LessonsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/progress-info': typeof ProgressInfoRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/print/$lessonId': typeof PrintLessonIdRoute
  '/scripture/epistles': typeof ScriptureEpistlesRoute
  '/scripture/gospels': typeof ScriptureGospelsRoute
  '/scripture/new-testament': typeof ScriptureNewTestamentRoute
  '/scripture/old-testament': typeof ScriptureOldTestamentRoute
  '/scripture/psalms-wisdom': typeof ScripturePsalmsWisdomRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-info': typeof CurriculumInfoRoute
  '/features': typeof FeaturesRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/lessons': typeof LessonsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/progress-info': typeof ProgressInfoRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/print/$lessonId': typeof PrintLessonIdRoute
  '/scripture/epistles': typeof ScriptureEpistlesRoute
  '/scripture/gospels': typeof ScriptureGospelsRoute
  '/scripture/new-testament': typeof ScriptureNewTestamentRoute
  '/scripture/old-testament': typeof ScriptureOldTestamentRoute
  '/scripture/psalms-wisdom': typeof ScripturePsalmsWisdomRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-info': typeof CurriculumInfoRoute
  '/features': typeof FeaturesRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/lessons': typeof LessonsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/progress-info': typeof ProgressInfoRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/print/$lessonId': typeof PrintLessonIdRoute
  '/scripture/epistles': typeof ScriptureEpistlesRoute
  '/scripture/gospels': typeof ScriptureGospelsRoute
  '/scripture/new-testament': typeof ScriptureNewTestamentRoute
  '/scripture/old-testament': typeof ScriptureOldTestamentRoute
  '/scripture/psalms-wisdom': typeof ScripturePsalmsWisdomRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/curriculum'
    | '/curriculum-info'
    | '/features'
    | '/generate'
    | '/help'
    | '/lessons'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/progress-info'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/team'
    | '/templates'
    | '/terms'
    | '/admin/dashboard'
    | '/article/$slug'
    | '/checkout/success'
    | '/lesson/$lessonId'
    | '/print/$lessonId'
    | '/scripture/epistles'
    | '/scripture/gospels'
    | '/scripture/new-testament'
    | '/scripture/old-testament'
    | '/scripture/psalms-wisdom'
    | '/series/$seriesId'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/curriculum'
    | '/curriculum-info'
    | '/features'
    | '/generate'
    | '/help'
    | '/lessons'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/progress-info'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/team'
    | '/templates'
    | '/terms'
    | '/admin/dashboard'
    | '/article/$slug'
    | '/checkout/success'
    | '/lesson/$lessonId'
    | '/print/$lessonId'
    | '/scripture/epistles'
    | '/scripture/gospels'
    | '/scripture/new-testament'
    | '/scripture/old-testament'
    | '/scripture/psalms-wisdom'
    | '/series/$seriesId'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/curriculum'
    | '/curriculum-info'
    | '/features'
    | '/generate'
    | '/help'
    | '/lessons'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/progress-info'
    | '/resources'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/team'
    | '/templates'
    | '/terms'
    | '/admin/dashboard'
    | '/article/$slug'
    | '/checkout/success'
    | '/lesson/$lessonId'
    | '/print/$lessonId'
    | '/scripture/epistles'
    | '/scripture/gospels'
    | '/scripture/new-testament'
    | '/scripture/old-testament'
    | '/scripture/psalms-wisdom'
    | '/series/$seriesId'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  CurriculumInfoRoute: typeof CurriculumInfoRoute
  FeaturesRoute: typeof FeaturesRoute
  GenerateRoute: typeof GenerateRoute
  HelpRoute: typeof HelpRoute
  LessonsRoute: typeof LessonsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProgressInfoRoute: typeof ProgressInfoRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  PrintLessonIdRoute: typeof PrintLessonIdRoute
  ScriptureEpistlesRoute: typeof ScriptureEpistlesRoute
  ScriptureGospelsRoute: typeof ScriptureGospelsRoute
  ScriptureNewTestamentRoute: typeof ScriptureNewTestamentRoute
  ScriptureOldTestamentRoute: typeof ScriptureOldTestamentRoute
  ScripturePsalmsWisdomRoute: typeof ScripturePsalmsWisdomRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-info': {
      id: '/progress-info'
      path: '/progress-info'
      fullPath: '/progress-info'
      preLoaderRoute: typeof ProgressInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum-info': {
      id: '/curriculum-info'
      path: '/curriculum-info'
      fullPath: '/curriculum-info'
      preLoaderRoute: typeof CurriculumInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture/psalms-wisdom': {
      id: '/scripture/psalms-wisdom'
      path: '/scripture/psalms-wisdom'
      fullPath: '/scripture/psalms-wisdom'
      preLoaderRoute: typeof ScripturePsalmsWisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture/old-testament': {
      id: '/scripture/old-testament'
      path: '/scripture/old-testament'
      fullPath: '/scripture/old-testament'
      preLoaderRoute: typeof ScriptureOldTestamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture/new-testament': {
      id: '/scripture/new-testament'
      path: '/scripture/new-testament'
      fullPath: '/scripture/new-testament'
      preLoaderRoute: typeof ScriptureNewTestamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture/gospels': {
      id: '/scripture/gospels'
      path: '/scripture/gospels'
      fullPath: '/scripture/gospels'
      preLoaderRoute: typeof ScriptureGospelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture/epistles': {
      id: '/scripture/epistles'
      path: '/scripture/epistles'
      fullPath: '/scripture/epistles'
      preLoaderRoute: typeof ScriptureEpistlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$lessonId': {
      id: '/print/$lessonId'
      path: '/print/$lessonId'
      fullPath: '/print/$lessonId'
      preLoaderRoute: typeof PrintLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  CurriculumInfoRoute: CurriculumInfoRoute,
  FeaturesRoute: FeaturesRoute,
  GenerateRoute: GenerateRoute,
  HelpRoute: HelpRoute,
  LessonsRoute: LessonsRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProgressInfoRoute: ProgressInfoRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  PrintLessonIdRoute: PrintLessonIdRoute,
  ScriptureEpistlesRoute: ScriptureEpistlesRoute,
  ScriptureGospelsRoute: ScriptureGospelsRoute,
  ScriptureNewTestamentRoute: ScriptureNewTestamentRoute,
  ScriptureOldTestamentRoute: ScriptureOldTestamentRoute,
  ScripturePsalmsWisdomRoute: ScripturePsalmsWisdomRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
